apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfdhgqn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gfdhgqn
  template:
    metadata:
      labels:
        app: gfdhgqn
    spec:
      containers:
      - image: okteto.dev/gfdhgqn:latest
        name: gfdhgqn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4cf591d2-0edc-45a1-b9ee-1a7cb5813af0"
        - name: Vless_Path
          value: "/vl5bdhss5"
        - name: Vmess_UUID
          value: "4cf591d2-0edc-45a1-b9ee-1a7cb5813af0"
        - name: Vmess_Path
          value: "/vm3vsksdg4"
        - name: Share_Path
          value: "/v2link"
